### ISSUE TITLE
run init script on the database

### ISSUE THREAD

**Issue by ezraroi** [michaelruocco/embedded-mysql-plugin#5]
Hi,
is it possible to run an init script that creates the database and a user with permissions to this database?

Or is it done by the plugin and using the configuration?

**Comment by michaelruocco** [comment]
Hi @ezraroi,

Would you want to do this so that you can use a tool like flyway to run database migrations against the created database?

I expect it would potentially be possible but it is not something I have really looked into before. Certainly the underlying [library](https://github.com/wix/wix-embedded-mysql) allows you to do run scripts as shown below:

`EmbeddedMysql mysqld = anEmbeddedMysql(config)
    .addSchema("aschema", ScriptResolver.classPathScript("db/001_init.sql"))
    .addSchema("aschema2", ScriptResolver.classPathScripts("db/*.sql"))
    .start();`

You are welcome to try and have a stab at implementing something that makes use of this. I will try and have a play to see how this might work but I am very busy at work at the moment so it likely won't be for at least a couple of weeks or so before I can find some time to have a look.

**Comment by ezraroi** [comment]
Sure ,thanks... yes i am using flyway for DB migration. I will play and if needed will add PR
